// Generated by CoffeeScript 1.9.1
(function() {
  requirejs.config({
    baseUrl: "js",
    paths: {
      Phaser: "../phaser.min"
    }
  });

  require(["Phaser", "boot", "load", "menu", "play"], function(Phaser, boot, load, menu, play) {
    "use strict";
    window.game = new Phaser.Game(500, 350, Phaser.AUTO, "gameDiv");
    game.globals = {
      score: 0
    };
    game.state.add("boot", new boot.BootState);
    game.state.add("load", new load.LoadState);
    game.state.add("menu", new menu.MenuState);
    game.state.add("play", new play.PlayState);
    return game.state.start("boot");
  });

}).call(this);

//# sourceMappingURL=game.js.map
