// Generated by CoffeeScript 1.9.1
(function() {
  "use strict";
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(["Phaser"], function(Phaser) {
    var MenuState, exports;
    exports = {};
    exports.MenuState = MenuState = (function(superClass) {
      extend(MenuState, superClass);

      function MenuState() {
        return MenuState.__super__.constructor.apply(this, arguments);
      }

      MenuState.prototype.create = function() {
        var nameLabel, startLabel, upKey;
        nameLabel = this.game.add.text(this.game.world.centerX, 80, "Name", {
          font: "50px Arial",
          fill: "#ffffff"
        });
        nameLabel.anchor.setTo(0.5, 0.5);
        startLabel = this.game.add.text(this.game.world.centerX, this.game.world.height - 80, "press the up arrow key to start", {
          font: "25px Arial",
          fill: "#ffffff"
        });
        startLabel.anchor.setTo(0.5, 0.5);
        this.game.add.tween(startLabel).to({
          angle: -2
        }, 500).to({
          angle: 2
        }, 500).loop().start();
        this.muteButton = this.game.add.button(20, 20, "mute", this.toggleSound, this);
        this.muteButton.input.useHandCursor = true;
        if (this.game.sound.mute) {
          this.muteButton.frame = 1;
        }
        upKey = this.game.input.keyboard.addKey(Phaser.Keyboard.UP);
        upKey.onDown.addOnce(this.start, this);
      };

      MenuState.prototype.toggleSound = function() {
        this.game.sound.mute = !this.game.sound.mute;
        this.muteButton.frame = this.game.sound.mute ? 1 : 0;
      };

      MenuState.prototype.start = function() {
        this.game.state.start("play");
      };

      return MenuState;

    })(Phaser.State);
    return exports;
  });

}).call(this);

//# sourceMappingURL=menu.js.map
