// Generated by CoffeeScript 1.9.1
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(["Phaser"], function(Phaser) {
    var BaseShip, exports;
    exports = {};
    exports.BaseShip = BaseShip = (function(superClass) {
      extend(BaseShip, superClass);

      BaseShip.prototype.maxHardPoints = 2;

      BaseShip.prototype.health = 100;

      BaseShip.prototype.maxCargo = 4;

      BaseShip.prototype.maxUtilPoints = 3;

      BaseShip.prototype.maxCrew = 6;

      BaseShip.prototype.minCrew = 3;

      function BaseShip(game, x, y, key, frame) {
        this.hardPoints = [];
        this.UtilPoints = [];
        this.Crew = [];
        BaseShip.__super__.constructor.call(this, game, x, y, key, frame);
      }

      return BaseShip;

    })(Phaser.Sprite);
    return exports;
  });

}).call(this);

//# sourceMappingURL=ship.js.map
